apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dedmmrf1i-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dedmmrf1i-go 
  name: dedmmrf1i-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dedmmrf1i-go
    weight: 100 
